apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:EbwmGgQPx3gzYdQMYaFul/Y+7v6xp5/cqSK7QzS3nlUtTHomXDSQejTAYnQ/wIu5LdRHY8FsgODI7+tNKGeLILpKcacDUY4IWU2AerT+v+cQXBbwgYWCu6CeYWcN2Q==,iv:uZ0pY91vH3R9/DQwSB2ETjDct5jtJWZQ1m+lkaPLl1o=,tag:s9WUfuJjLB3Y3eEdYQcG6A==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:LKpScAQYkTQsQGMulbIhkvk=,iv:bAht5in5S4Iivbdbg+3Sw7jGmh0ufCQFokYJSqQ/2X8=,tag:OXa8rkkShrmsc9HeFyXzow==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:kuLcrU2p8shaajkHt9doPQ/s3xRjvMvyV34=,iv:D16Ruz7hEk1cMxLnhBpWFlVUVOo547OBMcuRyPEzZHk=,tag:eh4dgKmsEiS5fVH/iHVyLw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:yAvkc01YYuu/etwbE2OUyDKNYSMSrGCXdYerXsEaSH56vfLt,iv:y785KOgtqHIDLKcIjg/pKc2WRQllw+xgzJom8vcEb4M=,tag:URrX1SsiHUqDi725qRccyw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3R1E3eTFYNUtXYVlQQ3hl
            OTJIMXpXdGVXcmw1OVR2WUY2VWxRNy9KdEdRCmYyNldwcmszOWFWS0NoZ1BYU0RY
            Mmx4V2orbVN0SFF4cFZZUDYwZ21BUG8KLS0tIGh1UklZM3VtejdQSXl6aERnZUhX
            Mkw0VEhna3dMMkRGSE1IYkVWV21samsK2dZT2GzLLNoCWrMQRkWHa44YkWUj5y2H
            6InHllIg8JPIT7QWFvtZTZkGV5Z1iBWGH6/CS80RYSBUUXSsy0y+nQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T07:53:39Z"
    mac: ENC[AES256_GCM,data:/vLfaqnCKy38BF3dJ8aVWAYoFKHn1iNL8WgzPAhvvMFCSLODp3Gcde4N76yQKMQ4W1rgXVVm8CpBXQIisITfCAV3HlNLtx3OgNRbw4WSZ3kMV2sPyZixREkzh/91tSEjUiUdfIoKsbwWUe3uZtiWEQ2kiDU78rUKo6z1kvj5wUY=,iv:B+oKRl3wiFvb4TpR6TpFRxIR4Y6abbIbsvaP3Po/YgM=,tag:sOLl8UXBM1tLEHnT1P/n+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
