apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:geiwrn6E/YbfQsNCeVnI0NxfYKlFoGJT1J+ccm2r9+KdjdXGcpueLQ==,iv:D8hIj8kT02f9+KQfY4mC9hXE4NZjxuOfpCV+0dcljkU=,tag:HzJp4z7pxo7uJKEt7Rn2GQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h5yphh2d690esp9gswsjgqggftum7629amnq7wk6m4dg02mtufzsjp9h0c
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvbXl3bnVaZGs3YlVYZjJ0
            Z05tVjBhUjJ4RGdwWXpMdDFpaEE3bHhtZW1BCjg2b1dGN1VzTkowaFoyNTVVKzZv
            RXVnYjkvRndQa3M0QU52ZXd2MisrVjgKLS0tIGJEZTllWDl6K1NTNW1GRXpqUHNJ
            M3AzNXVQYkhHVldOQk04bkpBVFQ3Q0UKUBOwwHl+VkvYRbMnAL3oSu+Gc4Z1/oEZ
            lEgouPVvpj6tipzZ8YpFp9MQp5UtAEBR80yEQ/l1HqPz30nJ45I/jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-31T07:53:39Z"
    mac: ENC[AES256_GCM,data:K/nPmTc7vcyhwF7sW4xcdb3s74nIRVNnIVUcfB4WhEBT10iSVOO8JZsAX5gyN5G0V1S/sc+3+hn9TAL8CnUrlPSoOBmdO7xP/HcVomjotB6tDywDRaioZeAHKYVhgJ9DJD+/bLDriCLzCsi5Prh6CKfcmoLn7TqP3HBCPz578fY=,iv:0aZfmXGPTZZXedL7YxdAUfIgrkmYKzyeIs+ft8D1H4k=,tag:GT8eqezoBkPbvIOG8AMWAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
